### ISSUE TITLE
Create a docker-compose file which will run each component in a separate container 

### ISSUE THREAD

**Issue by sionovd** [OperationalBina/PipeRT#96]
If we'll want to run components in separate containers/pods, then we'll use the same docker image for all of them, but each container would specify a different command to run in the image. 
The command could look something like this: 
`python -m pipert.core.component --cfg_path <component_cfg_path>`

The ability to define the container's command is supported in [Kubernetes](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#define-a-command-and-arguments-when-you-create-a-pod) and in [OpenShift](https://docs.openshift.com/container-platform/4.4/applications/deployments/managing-deployment-processes.html#deployments-exe-cmd-in-container_deployment-operations
).

**Comment by MayoG** [comment]
Is this issue is about creating the dockerfile for the component ?

Or creating the script that will generate the docker-compose file from the configuration file. but before doing that we should agree on a format for the config file further then what we have know for example, how we specify which components will be on one pod/service and maybe some other things.

We can make an example of a docker-compose file first and see that the new design will actually work. Is that what this issue is about ?

**Comment by sionovd** [comment]
We wont need to change the dockerfile - this issue is about adding an alternative docker-compose file which deploys the pipeline using multiple containers, each one containing a different component, instead of one container that contains the whole pipeline.

**Comment by MayoG** [comment]
But why we are making it ? because of this ? 

>We can make an example of a docker-compose file first and see that the new design will actually work. Is that what this issue is about ?

**Comment by sionovd** [comment]
Yep :)
